helm:
  parameters:
  - name: api.image.name
    value: docker.io/funera1/hikky-api
    forcestring: true
  - name: api.image.tag
    value: latest@dummy
    forcestring: true
  - name: db.image.name
    value: docker.io/funera1/hikky-db
    forcestring: true
  - name: db.image.tag
    value: latest@dummy
    forcestring: true
